services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    hostname: minecraft
    environment:
      EULA: "TRUE"
      DIFFICULTY: "normal"
      LEVEL_NAME: "Mungcrango"
    ports:
      - "19132:19132/udp"
    volumes:
      - ${MINECRAFT_DIR}:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
  netbird:
    image: netbirdio/netbird:latest
    volumes:
      - ${NETBIRD_DIR}:/var/lib/netbird
    network_mode: "service:minecraft"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    restart: unless-stopped
