keys:
  - &tyler age1mv6z5g3ksndaydrefzz9tq4k8xftwyy3x0qlfkr4k93ypxm0sfxqcedc3u
  - &bubblegum age17pcp20lu03cx7xe93lkud4tmd9u952f867zg68wkdjh0sp7hspvqa2xm27
  - &coconut age1ut47xkln08l23sdjtl6h6uujwc7tp0fk84hw6gv8qllm7lcuhy7qv8zafw
creation_rules:
  - path_regex: (^|/)secrets/[^/]*\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *tyler
        - *bubblegum
        - *coconut
