services:
  dash-app:
    image: glanceapp/glance:${GLANCE_VERSION}
    expose:
      - 8080
    environment:
      - MINIFLUX_TOKEN=${MINIFLUX_TOKEN}
      - MINIFLUX_API_URL=${MINIFLUX_URL}
      - MINIFLUX_LINKS_URL=${MINIFLUX_URL}
    volumes:
      - ${CONFIG_DIR}:/app/config
    networks:
      - cluster

networks:
  cluster:
    external: true
