services:
  hole:
    image: pihole/pihole:${PIHOLE_VERSION:-latest}
    hostname: hole
    dns:
      - 9.9.9.9
    volumes:
      - ${DATA_DIR}:/etc/pihole
      - ${DNSMASQ_DIR}:/etc/dnsmasq.d
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PASSWORD}
    network_mode: host
