services:
  search:
    image: ghcr.io/fccview/degoog:latest
    volumes:
      - ${DATA_DIR}:/app/data
    expose: 4444
    restart: unless-stopped
    networks:
      - cluster

networks:
  cluster:
    external: true
