services:
  containers:
    container_name: container-monitor
    image: "portainer/portainer-ce:${PORTAINER_VERSION:-lts}"
    expose:
      - 9000
    volumes:
      - /home/tyler/apps/portainer/data:/data
    networks:
      - cluster
      - container-monitoring

networks:
  cluster:
    external: true
  container-monitoring:
    external: true
