"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
[](cyan)\
$os\
$username\
$hostname\
[](fg:cyan bg:blue)\
$directory\
[](fg:blue bg:brown)\
$git_branch\
$git_status\
[](fg:brown bg:purple)\
$rust\
$golang\
$nodejs\
$java\
$python\
[](fg:purple bg:base02)\
$docker_context\
[](fg:base02 bg:base01)\
$time\
[ ](fg:base01)\
$line_break$character"""

[os]
disabled = false
style = "bold bg:cyan fg:black"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
NixOS = "󱄅 "

[username]
show_always = true
style_user = "bg:cyan fg:black"
style_root = "bg:cyan fg:black"
format = '[$user]($style)'

[hostname]
style = "bg:cyan fg:black"
format = "[ @ $hostname ]($style)"
ssh_only = false

[directory]
style = "bg:blue fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:brown"
format = '[[ $symbol $branch ](fg:black bg:brown)]($style)'

[git_status]
style = "bg:brown"
format = '[[($all_status$ahead_behind )](fg:black bg:brown)]($style)'

[nodejs]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:black bg:purple)]($style)'

[rust]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:black bg:purple)]($style)'

[golang]
symbol = "󰟓"
style = "bg:purple"
format = '[[ $symbol( $version)( $mod_version) ](fg:black bg:purple)]($style)'

[java]
symbol = " "
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:black bg:purple)]($style)'

[python]
symbol = ""
style = "bg:purple"
format = '[[ $symbol( $version) ](fg:black bg:purple)]($style)'

[docker_context]
symbol = ""
style = "bg:base02"
format = '[[ $symbol( $context) ](fg:base06 bg:base02)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:base01"
format = '[[  $time ](fg:base06 bg:base01)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green_green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
