services:
  media:
    container_name: media-server
    image: lscr.io/linuxserver/jellyfin:${JELLYFIN_VERSION}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - "${CONFIG_DIR}:/config"
      - "${MOVIE_DIR}:/data/movies"
      - "${SHOW_DIR}:/data/tvshows"
      - "${MUSIC_DIR}:/data/music"
    networks:
      - proxy
    restart: unless-stopped

  scrobbler:
    container_name: media-scrobbler
    image: foxxmd/multi-scrobbler:${SCROBBLER_VERSION}
    depends_on:
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JELLYFIN_ID=default
      - JELLYFIN_URL=http://media:8096
      - JELLYFIN_USER=${JELLYFIN_USER}
      - JELLYFIN_APIKEY=${JELLYFIN_APIKEY}
      - LASTFM_ID=default
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - LASTFM_SECRET=${LASTFM_SECRET}
      - BASE_URL=${SCROBBLER_BASE_URL}
    volumes:
      - "${SCROBBLER_CONFIG_DIR}:/config"
    expose:
      - 9078
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: private
