timezone = "America/Chicago"

[networks.proxy]
  name = "private"

[networks.vlan]
  name = "vlan"
  subnet = "192.168.0.0/24"
  gateway = "192.168.0.1"
  parent = "eno1"

[backup]
  apps.directory = "/home/tyler/backup/apps"
  data.directory = "/home/tyler/backup/data"

[homeServer]
  directory = "/home/tyler/homeserver"
