x-deploy: &placement
  deploy:
    placement:
      constraints:
        - node.hostname == bubblegum

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ${DATA_DIR}/synapse:/var/lib/postgresql/data
    networks:
      - matrix-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d synapse"]
      interval: 10s
      timeout: 5s
      retries: 5
    <<: *placement

  server:
    image: matrixdotorg/synapse:latest
    environment:
      SYNAPSE_SERVER_NAME: ${BASE_DOMAIN}
      SYNAPSE_REPORT_STATS: "no"
      POSTGRES_HOST: db
      POSTGRES_DB: synapse
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${CONFIG_DIR}/synapse:/data
    expose:
      - 8008
    ports:
      - "8448:8448"  # Federation API
    networks:
      - cluster
      - matrix-network
    depends_on:
      db:
        condition: service_healthy
    command: run
    <<: *placement

  auth:
    image: ghcr.io/element-hq/matrix-authentication-service:latest
    expose:
      - 8080
    volumes:
      - ${CONFIG_DIR}/mas:/config
    networks:
      - cluster
      - matrix-network
    depends_on:
      auth-db:
        condition: service_healthy
    command: ["server"]
    environment:
      - MAS_CONFIG=/config/config.yaml
    <<: *placement

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth
    volumes:
      - ${DATA_DIR}/auth:/var/lib/postgresql
    networks:
      - matrix-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -d auth"]
      interval: 10s
      timeout: 5s
      retries: 5
    <<: *placement

  client:
    image: vectorim/element-web:latest
    expose:
      - 80
    volumes:
      - ${CONFIG_DIR}/element/config.json:/app/config.json
    networks:
      - cluster
      - matrix-network
    depends_on:
      - server
    <<: *placement

networks:
  cluster:
    external: true
  matrix-network:
    driver: bridge

